### ISSUE TITLE
ISSUES

### ISSUE THREAD

**Issue by cvalencia1991** [cvalencia1991/Portfolio#15]

**Comment by OscarFMdev** [comment]
**Good job so far!** Your project looks almost like Figma design. The only thing that I've seen in your project I that:

- [ ] I think it would look better if you use Figma images for the desktop version and for the pop up.

**Comment by Miliyonayalew** [comment]
Your project looks excellent 👍💯,  I see that you worked hard but, I have a few comments:

-  You must stop storing the data in the local storage when the email field has invalid input.

**Comment by didierganthier** [comment]
Well done! Just one thing I'd like to mention:
- [ ] Your `localStorage` data should be loaded to the input fields when page is loaded

**Comment by cvalencia1991** [comment]
it's fix
